grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 5
    verbose: 2

model_selection:
  module_0:
    class: LinearRegression
    modeule: sklearn.linear_model
    params:
      fit_intercept: True
    search_param_grid:
      fit_intercept:
      - True
      - False

  module_1:
    class: Ridge
    module: sklearn.linear_model
    params:
      fit_intercept: True
      alpha: 1.0
    search_param_grid:
      fit_intercept:
      - True
      - False
      alpha:
      - 0.05
      - 0.1
      - 0.2
      - 0.5
      - 0.75
      - 1
      solver:
      - auto
      - svd
      - lbfgs

  module_2:
    class: Lasso
    module: sklearn.linear_model
    params:
      fit_intercept: True
      alpha: 1.0
      warm_start: True
      selection: random
    search_param_grid:
      alpha:
      - 0.05
      - 0.1
      - 0.2
      - 0.5
      - 0.75
      - 1
      warm_star:
      - True
      - False

      selection:
      - random
      - cyclic


  module_3:
    class: DecisionTreeRegressor
    module: sklearn.tree
    params:
      criterion: squared_error
      max_depth: 3
      min_samples_leaf: 2
      max_features: auto
      max_leaf_nodes: 2

    search_param_grid:
      criterion:
      - squared_error
      - friedman_mse
      - absolute_error
      - poisson

      max_depth:
      - 3
      - 4
      - 5
      - 6
      min_samples_leaf:
      - 1
      - 2
      - 3
      - 4
      max_features:
      - auto
      - sqrt
      - log2

      max_leaf_nodes:
      - 1
      - 2
      - 3

  module_4:
    class: RandomForestRegressor
    module: sklearn.ensemble
    params:
      n_estimators: 50
      n_jobs: -1
      criterion: squared_error
      max_depth: 3
      min_samples_leaf: 2
      max_features: auto
      max_leaf_nodes: 2

    search_param_grid:
      criterion:
      - squared_error
      - friedman_mse
      - absolute_error
      - poisson

      max_depth:
      - 3
      - 4
      - 5
      - 6
      min_samples_leaf:
      - 1
      - 2
      - 3
      - 4
      max_features:
      - auto
      - sqrt
      - log2

      max_leaf_nodes:
      - 1
      - 2
      - 3
      oob_score:
      - True
      - False
      n_estimators:
      - 100
      - 150
      - 175


  module_5:
    class: AdaBoostRegressor
    module: sklearn.ensemble
    params:
      n_estimators: 100
      loss: linear
      learning_rate: 1.0

    search_param_grid:
      n_estimators:
      - 100
      - 150
      - 175
      loss:
      - linear
      - square
      - exponential
      learning_rate:
      - 0.05
      - 0.1
      - 0.5
      - 0.75


  module_6:
    class: GradientBoostingRegressor
    module: sklearn.ensemble
    params:
      n_estimators: 100
      loss: squared_error
      criterion: friedman_mse
      min_samples_leaf: 1
      max_depth: 4

    search_param_grid:
      criterion:
      - squared_error
      - friedman_mse
      n_estimators:
      - 100
      - 150
      - 175
      loss:
      - squared_error
      - absolute_error
      - huber
      - quantile

      min_samples_leaf:
      - 1
      - 2
      - 3
      - 4

      max_depth:
      - 3
      - 4
      - 5
      - 6



