categorical_columns:
- ocean_proximity
columns:
  households: float64
  housing_median_age: float64
  latitude: float64
  longitude: float64
  median_income: float64
  ocean_proximity: object
  population: float64
  total_bedrooms: float64
  total_rooms: float64
  median_house_value: float64
domain_value:
  ocean_proximity:
  - NEAR BAY
  - <1H OCEAN
  - INLAND
  - NEAR OCEAN
  - ISLAND
numerical_columns:
- longitude
- latitude
- housing_median_age
- total_rooms
- total_bedrooms
- population
- households
- median_income

target_column: median_house_value
